#!/bin/bash
# Original copyright Amazon.com, Inc.
# Original SPDX-License-Identifier: MIT-0
# Modified copyright Architect
# Modified SPDX-License-Identifier: Apache-2.0

set -euo pipefail
exec "/opt/arc-telemetry/index.js"
